name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        working-directory: .
        run: npm install && npm run build

      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: ./build
